### ISSUE TITLE
Multiprocess Problem

### ISSUE THREAD

**Issue by ChadCSong** [theoneee/DynamicWallpaper#1]
https://github.com/Theoneee/DynamicWallpaper/blob/b9ff4499eadc3978af6391606f878ddb638e742b/app/src/main/java/com/theone/dynamicwallpaper/ui/VideoFragment.java#L155

This is multiprocess problem. SharedPreference is standalone in each process, you can't access the string  in process1 witch you saved in process2 directly.
You can solve this problem by Messenger or AIDL. 
Otherwise you also can use single process.

**Comment by Theoneee** [comment]
Emmmmm, can you speak Chinese...  My English is pool.

**Comment by Theoneee** [comment]
https://blog.csdn.net/hzw2017/article/details/81090319
https://www.cnblogs.com/makaruila/p/4869912.html
我看了这两篇关于用Msssenger客户端和服务端通信。都是在onBind里这样处理。
```    
    @Override
    public IBinder onBind(Intent intent) {
        return mMessenger.getBinder();
    }
```

可是在WallpaperService

  ```
   /**
     * Implement to return the implementation of the internal accessibility
     * service interface.  Subclasses should not override.
     */
    @Override
    public final IBinder onBind(Intent intent) {
        return new IWallpaperServiceWrapper(this);
    }
```

``` 
    /**
     * Implements the internal {@link IWallpaperService} interface to convert
     * incoming calls to it back to calls on an {@link WallpaperService}.
     */
    class IWallpaperServiceWrapper extends IWallpaperService.Stub {
        private final WallpaperService mTarget;

        public IWallpaperServiceWrapper(WallpaperService context) {
            mTarget = context;
        }

        @Override
        public void attach(IWallpaperConnection conn, IBinder windowToken,
                int windowType, boolean isPreview, int reqWidth, int reqHeight, Rect padding) {
            new IWallpaperEngineWrapper(mTarget, conn, windowToken,
                    windowType, isPreview, reqWidth, reqHeight, padding);
        }
    }
```

这样好像处理不了。。

**Comment by ChadCSong** [comment]
嗯。。。看了一下，还真是，这的确是个问题。
不过办法还是有的，比如共享文件，或者Socket通信
我觉得封装一套Socket的通信工具比较靠谱，比如：
https://stackoverflow.com/questions/20915926/communicate-with-a-wallpaperservice

**Comment by Theoneee** [comment]
不过我用SP没有出现传递失败的情况。。。
